### PR TITLE
Readme::Usage reformat

### PR DESCRIPTION
**Pull request by shalecraig**
I re-formatted some of the readme, specifically the *Usage* part.

Feel free to merge/ignore if you don't like it.

### CODE REVIEW

**Comment by mibk** [comment]
Thank you. Could you please squash it into something like: `README: reformat usage`?

**Comment by mibk** [comment]
@shalecraig Or should I do the squash instead of you?

**Comment by shalecraig** [comment]
I'll do it. Give me 20minutes.

On Thursday, June 11, 2015, Michal Bohuslávek <notifications@github.com>
wrote:

> @shalecraig <https://github.com/shalecraig> Or should I do the squash
> instead of you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mibk/dupl/pull/4#issuecomment-111169925>.
>


-- 
----------------------------------------------------------------
Shale Craig
shalecraig@gmail.com

**Comment by shalecraig** [comment]
Done.

**Comment by mibk** [comment]
Thank you :-).

**Pull request closed without merging**
